Repository wam82/teamname-soen341project2023, pull requests merged in 2023-02, with the labels that each got.

#34 Milestone/init project
  app.tsx
  index.html
  package-lock.json
  package.json
  projectname.njsproj
  projectname.njsproj.user
  projectname.sln
  server.js
  tsconfig.json
  webpack-config.js
Labels: urgent

#35 created folder for sprint
  Sprint1/Sprint1.txt
Labels: urgent

#43 [login] Created login page and header
  .gitignore
  app.tsx
  app/README.md
  app/package-lock.json
  app/package.json
  app/public/favicon.ico
  app/public/index.html
  app/public/logo192.png
  app/public/logo512.png
  app/public/manifest.json
  app/public/robots.txt
  app/src/App.tsx
  app/src/Header/Header.css
  app/src/Header/Header.js
  app/src/LoginPage/LoginPage.css
  app/src/LoginPage/LoginPage.js
  app/src/index.css
  app/src/index.tsx
  app/src/react-app-env.d.ts
  app/tsconfig.json
  index.html
  package-lock.json
  package.json
  projectname.njsproj
  projectname.njsproj.user
  projectname.sln
  server.js
  tsconfig.json
  webpack-config.js
Labels: epic, user story/employer, user story/student

#45 [database] Created a back-end
  app/package-lock.json
  app/package.json
  app/src/LoginPage/LoginPage.js
  app/src/react-app-env.d.ts
  obj/Debug/projectname.njsproj.AssemblyReference.cache
  server/package-lock.json
  server/package.json
  server/server.js
Labels: urgent, back-end, database

#49 Create tool to link pages using react router dom
  app/package-lock.json
  app/package.json
Labels: front-end
